name: Generate Plugins JSON File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  process-json:
    name: Generate Plugins JSON File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags  # Fetch all tags from the remote
          latest_tag=$(git describe --tags --abbrev=0)
          if [[ $latest_tag == v* ]]; then
            latest_tag=${latest_tag:1}
          fi
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Process JSON
        run: |
          core_input="core_plugins/plugins.json"
          community_input="community_plugins.json"

          output_file="plugins.json"
          
          if [ -f "$core_input" ]; then
            core_data=$(cat "$core_input")
          else
            echo "Core plugins file not found: $core_input" && exit 1
          fi
          if [ -f "$community_input" ]; then
            community_data=$(cat "$community_input")
          else
            community_data="[]"
          fi
          echo "$core_data" | jq --arg core_version "$latest_tag" --argjson community "$community_data" \
            '{core_version: $core_version, core: ., community: $community}' > "$output_file"

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugins.json
          git diff --cached --exit-code || (git commit -m "Generated plugins.json" && git push)


