name: Process JSON File

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour
  push:
    paths:
      - 'core_plugins/plugins.json'

jobs:
  process-json:
    name: Process and Update Plugins JSON File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process JSON
        run: |
          input_file="core_plugins/plugins.json"
          output_file="plugins.json"
          if [ -f "$input_file" ]; then
            jq '{core: ., community: []}' "$input_file" > "$output_file"
          else
            echo "Input file not found: $input_file" && exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugins.json
          git commit -m "Generated plugins.json"
          git push
