name: Process JSON File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour

jobs:
  process-json:
    name: Process and Update Plugins JSON File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags  # Fetch all tags from the remote
          latest_tag=$(git describe --tags --abbrev=0)
          if [[ $latest_tag == v* ]]; then
            latest_tag=${latest_tag:1}
          fi
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Process JSON
        run: |
          input_file="core_plugins/plugins.json"
          output_file="plugins.json"
          if [ -f "$input_file" ]; then
            jq --arg core_version "$latest_tag" \
              '{core_version: $core_version, core: ., community: []}' "$input_file" > "$output_file"
          else
            echo "Input file not found: $input_file" && exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugins.json
          git diff --cached --exit-code || (git commit -m "Generated plugins.json" && git push)


